### ISSUE TITLE
Support RethinkDB 2.0 features

### ISSUE THREAD

**Issue by mfenniak** [mfenniak/rethinkdb-net#194]
https://groups.google.com/forum/#!topic/rethinkdb-dev/3qxVOW05Y58

* ~~New protocol version, V0_4, allows execution of multiple commands in parallel on one connection.  Theoretically rethinkdb-net should work fine with just upgrading to this protocol version, but it will require testing.~~ (Completed in #211)
* ~~Change in semantics of ResponseType enums.~~  Resolved during compatibility upgrade.
* ~~between command no longer accepts null as boundary conditions; minval/maxval are used instead.~~  This isn't really a 'feature', so, we'll use the deprecated version to maintain compatibility and avoid a change.
* ~~indexes_of has been renamed to offsets_of~~  Compatibility change, not feature; not used in rethinkdb-net yet.
* return_changes optarg on writes.
* ~~changes query can be run on result of get_all and union.~~
* changes command has a new optarg include_state.
* ~~Update CI.~~ Compatibility, not feature.

**Comment by robzhu** [comment]
I just tried out the (person) sample on the project page and hit a protocol exception when connecting to RethinkDB 2.0. I reverted to 1.16 and confirmed that everything worked again. Here's a link to the 2.0 docker image I used: https://registry.hub.docker.com/u/robzhu/rethinkdb/

**Comment by mfenniak** [comment]
Hey @robzhu.  I just committed the code from the README into a project in the solution, and ran it against RethinkDB 2.0.0-1 on OSX.  I didn't encounter any issue.  Can you provide the exception that you encountered?

**Comment by robzhu** [comment]
@mfenniak, I just tried to repeat it as well and it's now working against 2.0 (different machine). Please ignore this issue for now until I can get a reliable repro.

**Comment by robzhu** [comment]
Here is the output on the machine where the sample fails against 2.0:

Exception occurred in Connection.ReadLoop: RethinkDb.RethinkDbInternalErrorException: Unexpected JSON state
   at RethinkDb.Protocols.Version_0_3_Json.ReadJsonResponse(JsonReader json, Int64 token, ILogger logger)
   at RethinkDb.Protocols.Version_0_3_Json.<ReadResponseFromStream>c__async1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RethinkDb.Connection.<ReadLoop>c__async2.MoveNext(); this connection will no longer function correctly, no error recovery will take place
1 queries were still waiting for responses from a connection that is closing; they'll receive exceptions instead

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> RethinkDb.RethinkDbInternalErrorException: Unexpected exception in ReadLoop prevented this query from returning data ---> R
   at RethinkDb.Protocols.Version_0_3_Json.ReadJsonResponse(JsonReader json, Int64 token, ILogger logger)
   at RethinkDb.Protocols.Version_0_3_Json.<ReadResponseFromStream>c__async1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RethinkDb.Connection.<ReadLoop>c__async2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RethinkDb.Connection.<InternalRunQuery>c__async3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RethinkDb.Connection.<RunAsync>c__async4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RethinkDb.ConnectionFactories.ReliableConnectionFactory.ReliableConnectionWrapper.<RetryRunAsync>c__async0`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at RethinkDb.TaskUtilities.ExecuteSynchronously[T](Func`1 taskDelegate)
   at RethinkDb.SynchronousApiExtensions.Run[T](IConnection connection, IScalarQuery`1 queryObject, IQueryConverter queryConverter, Nullable`1 cancellationToken)
   at RethinkSample.Program.Main(String[] args) in c:\Users\redacted\Documents\Visual Studio 2013\Projects\RethinkSample\RethinkSample\Program.cs:line 28

**Comment by mfenniak** [comment]
Is it possible that you're connecting to RethinkDB's intracluster communication port, rather than the client driver port?  Or... is there some other networking factor at play?

If those aren't the issue, can you turn on rethinkdb-net's logging at the highest level (eg. ```<defaultLogger enabled="true" category="Debug"/>```) and paste the output here?  I can't reproduce this, so, there's no other way to proceed here other than analyzing log data.
